# Generated by Django 3.2.3 on 2021-07-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_id_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products_id',
            new_name='products',
        ),
    ]
