# Generated by Django 3.2.3 on 2021-07-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='img_url',
        ),
    ]
