# Generated by Django 3.2.3 on 2021-07-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
