# Generated by Django 3.2.3 on 2021-07-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='product_id',
            new_name='product',
        ),
    ]
